name: 'vmmeter-action'
description: 'Meter CPU load and RAM for a job'
inputs:
  createSummary: # id of input
    description: 'Print summary of metering'
    required: false
    default: 'true'
outputs:
  start-time: # id of output
    description: 'Start time of metering'
  end-time: # id of output
    description: 'End time of metering'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

