name: 'Hello World'
description: 'Greet someone and record the time'
outputs:
  start-time: # id of output
    description: 'Start time of metering'
  end-time: # id of output
    description: 'End time of metering'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

